$a="a";   
$b="b";
$c="c";
$d="ab";
$e="d";
if ($a =~ m/[a|b|c]/) { print "yes!\n"; } else { print "no !\n"; }
if ($b =~ m/[a|b|c]/) { print "yes!\n"; } else { print "no !\n"; }
if ($c =~ m/[a|b|c]/) { print "yes!\n"; } else { print "no !\n"; }
if ($d =~ m/[a|b|c]/) { print "yes!\n"; } else { print "no !\n"; }
if ($e =~ m/[a|b|c]/) { print "yes!\n"; } else { print "no !\n"; }
